# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablas.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from fpdf import FPDF

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(612, 655)
        Dialog.setMaximumSize(QtCore.QSize(612, 655))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("tablas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.threadmanager = QtCore.QThreadPool()
        self.screen = QtWidgets.QTextEdit(Dialog)
        self.screen.setGeometry(QtCore.QRect(10, 70, 591, 201))
        self.screen.setMinimumSize(QtCore.QSize(591, 201))
        self.screen.setMaximumSize(QtCore.QSize(591, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.screen.setFont(font)
        self.screen.setObjectName("screen")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 290, 591, 269))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.pushButton_comma = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_comma.sizePolicy().hasHeightForWidth())
        self.pushButton_comma.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_comma.setFont(font)
        self.pushButton_comma.setStyleSheet("")
        self.pushButton_comma.setObjectName("pushButton_comma")
        self.gridLayout.addWidget(self.pushButton_comma, 3, 0, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 2, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_00 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_00.sizePolicy().hasHeightForWidth())
        self.pushButton_00.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_00.setFont(font)
        self.pushButton_00.setStyleSheet("")
        self.pushButton_00.setObjectName("pushButton_00")
        self.gridLayout.addWidget(self.pushButton_00, 3, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 0, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_0.sizePolicy().hasHeightForWidth())
        self.pushButton_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("")
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 3, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButton_crear = QtWidgets.QPushButton(Dialog)
        self.pushButton_crear.setGeometry(QtCore.QRect(10, 580, 192, 62))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_crear.sizePolicy().hasHeightForWidth())
        self.pushButton_crear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_crear.setFont(font)
        self.pushButton_crear.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(0, 143, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 85, 0);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color:white\n"
"}")
        self.pushButton_crear.setDefault(True)
        self.pushButton_crear.setObjectName("pushButton_crear")
        self.pushButton_borrar = QtWidgets.QPushButton(Dialog)
        self.pushButton_borrar.setGeometry(QtCore.QRect(210, 580, 192, 62))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_borrar.sizePolicy().hasHeightForWidth())
        self.pushButton_borrar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_borrar.setFont(font)
        self.pushButton_borrar.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(255, 85, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(236, 0, 0);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color:white\n"
"}")
        self.pushButton_borrar.setObjectName("pushButton_borrar")
        self.pushButton_guardar = QtWidgets.QPushButton(Dialog)
        self.pushButton_guardar.setGeometry(QtCore.QRect(410, 580, 192, 62))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_guardar.sizePolicy().hasHeightForWidth())
        self.pushButton_guardar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_guardar.setFont(font)
        self.pushButton_guardar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 110, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 0, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color:white\n"
"}")
        self.pushButton_guardar.setObjectName("pushButton_guardar")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 591, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        self.pushButton_borrar.clicked.connect(self.screen.clear) # type: ignore
        self.pushButton_borrar.clicked.connect(self.lineEdit.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton_guardar.setObjectName("pushButton_guardar")
        self.pushButton_00.clicked.connect(lambda x:self.click("00"))
        self.pushButton_0.clicked.connect(lambda x:self.click("0"))
        self.pushButton_1.clicked.connect(lambda x:self.click("1"))
        self.pushButton_2.clicked.connect(lambda x:self.click("2"))
        self.pushButton_3.clicked.connect(lambda x:self.click("3"))
        self.pushButton_4.clicked.connect(lambda x:self.click("4"))
        self.pushButton_5.clicked.connect(lambda x:self.click("5"))
        self.pushButton_6.clicked.connect(lambda x:self.click("6"))
        self.pushButton_7.clicked.connect(lambda x:self.click("7"))
        self.pushButton_8.clicked.connect(lambda x:self.click("8"))
        self.pushButton_9.clicked.connect(lambda x:self.click("9"))
        self.pushButton_comma.clicked.connect(lambda x:self.click(","))
        self.pushButton_crear.released.connect(self.create)
        self.pushButton_guardar.released.connect(self.save)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tablas de Multiplicar"))
        self.screen.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.pushButton_2.setText(_translate("Dialog", "2"))
        self.pushButton_comma.setText(_translate("Dialog", ","))
        self.pushButton_1.setText(_translate("Dialog", "1"))
        self.pushButton_4.setText(_translate("Dialog", "4"))
        self.pushButton_00.setText(_translate("Dialog", "00"))
        self.pushButton_9.setText(_translate("Dialog", "9"))
        self.pushButton_7.setText(_translate("Dialog", "7"))
        self.pushButton_6.setText(_translate("Dialog", "6"))
        self.pushButton_3.setText(_translate("Dialog", "3"))
        self.pushButton_5.setText(_translate("Dialog", "5"))
        self.pushButton_0.setText(_translate("Dialog", "0"))
        self.pushButton_8.setText(_translate("Dialog", "8"))
        self.pushButton_crear.setText(_translate("Dialog", "Crear"))
        self.pushButton_borrar.setText(_translate("Dialog", "Borrar"))
        self.pushButton_guardar.setText(_translate("Dialog", "Guardar"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "ingrese un numero o un rango separado por  una coma"))


    def click(self, d):
        self.lineEdit.insert(str(d))
    def create(self):
        self.screen.clear()
        self.range = self.lineEdit.text()
        if "," not in self.range:
                try:
                        for x in range(int(self.range),int(self.range)+1):
                                for y in range(1,11):
                                        t = f"{x}x{y}={x*y}"
                                        self.screen.append(t)
                except Exception as e:
                        if self.range == "":
                                QtWidgets.QMessageBox.critical(None,"Error", "Ingrese al menos un numero")
                        else:
                                QtWidgets.QMessageBox.critical(None,"Error", "revise los datos ingresados")
                        
        else:
                self.range = self.lineEdit.text().split(",")
                try:
                        for x in range(int(self.range[0]),int(self.range[1])+1):
                                for y in range(1,11):
                                        t = f"{x}x{y}={x*y}"
                                        self.screen.append(t)
                                self.screen.append("\n")
                except Exception as e:
                        QtWidgets.QMessageBox.critical(None,"Error", "Revise sus datos ingresados")

    def save(self):
        file = QtWidgets.QFileDialog.getSaveFileName(None,"archivos",None,"PDF (*.pdf);;Texto (*.txt);;HTML (*.html)")
        if file:
                if file[0].endswith("txt"):
                        con = self.screen.toPlainText()
                        with open(file[0],"w") as f:
                                f.write(con)
                        msg = QtWidgets.QMessageBox.about(None, "Guardar", str("Archivo guardado como:"+file[0]))
                elif file[0].endswith("html"):
                        con = self.screen.toHtml()
                        with open(file[0],"w") as f:
                                f.write(con)
                        msg = QtWidgets.QMessageBox.about(None, "Guardar", str("Archivo guardado como:"+file[0]))
                elif file[0].endswith("pdf"):
                        name = file[0]
                        con = self.screen.toPlainText()
                        pdf = FPDF()
                        pdf.set_font("arial",size=12)
                        pdf.add_page()
                        pdf.multi_cell(80,5,con)
                        pdf.output(name)
                        msg = QtWidgets.QMessageBox.about(None, "Guardar", str("Archivo guardado como: "+file[0]))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
